# Generated by Django 4.0.6 on 2022-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_cartitem_user_alter_product_price_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='qty_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
